### ISSUE TITLE
Question on instantiation

### ISSUE THREAD

**Issue by bjornharvold** [mreuvers/typescript-logging#1]
Great code here. I wonder where is the best place to instantiate the LoggerFactory? Does it occur in every class or should it just happen one time?

An example on this would be great. I am working with Angular CLI.

Cheers,
Bjorn

**Comment by mreuvers** [comment]
Hello Bjorn,

Glad you like it. :)

As you work with Angular, I assume here you're probably building a single page app? In that case the LoggerFactory can easily live in just one place and be configured there, for example like this:

LoggerOptions.ts
--------------------------------------
`import {LFService, LoggerFactoryOptions, LogGroupRule, LogLevel} from "typescript-logging"

const loggerOptions = new LoggerFactoryOptions()
  .addLogGroupRule(new LogGroupRule(new RegExp("model\\..+"), LogLevel.Debug))
  .addLogGroupRule(new LogGroupRule(new RegExp("service\\..+"), LogLevel.Debug));
export const loggerFactory = LFService.createLoggerFactory(loggerOptions);
`

Then in a module/class where you need it you just import the exported 'loggerFactory' from above.

Example.ts
----------------------
`import {loggerFactory} from "./LoggerConfig";

export class Example {
  private log = loggerFactory.getLogger("service.MyService");  

  someFunction(): void {
    log.debugc(() => "Doing something amazing here");
    ...
  }
}
`

I will add this (or a similar) example later with an update, it should be clear after all. :)

As a note for you: There will be a major update coming in roughly 1-2 months from now (bit depending on free time), the current logging mechanism will remain working (except there will be some of the classes moved to different module files, so you may need to reimport them in your modules, the api on itself will not break). 
As long as the version is not yet on 1.0.0, I sometimes have to change a few things for the next major upgrade to come. Once 1.0.0 things will be fully backwards compatible. I just wanted you to be aware of this. I try not to break api's.

The major upgrade may be interesting for you too, as there will a complete additional new logging mechanism compared to the current one (but you will either love it or hate it, I don't think there is a between). ;)
In any case the current one remains working as is (safe for the reimports you need to do).

Thanks,
Martijn

**Comment by bjornharvold** [comment]
Thank you Martijn! Great answer :-)
