### ISSUE TITLE
Logger not display debug messages in Chrome

### ISSUE THREAD

**Issue by Lexanius** [mreuvers/typescript-logging#10]
Hiho,

The debug messages is not shown in Chrome console. The trace and info will. In Firefox it will show the debug messages.
`logger.info("" + logger.isDebugEnabled())` will display true for the logger

Usage: a ionic 2 project.

Chrome: Version 58.0.3029.96 (64-bit)

My config: 
```
import { LoggerFactoryOptions, LFService, LogGroupRule, LogLevel, LoggerFactory } from "typescript-logging";
export { Logger } from 'typescript-logging'
const options = new LoggerFactoryOptions()
    .addLogGroupRule(new LogGroupRule(new RegExp(".+"), LogLevel.Trace));

export const LogFactory: LoggerFactory = LFService.createLoggerFactory(options);
```

`const logger: Logger = LogFactory.getLogger("Name")`

**Comment by mreuvers** [comment]
Hello @Lexanius 

Thank you for logging the issue.

Can you please check that in the chrome console, at the top - the filter is set to "Verbose"? That should make the debug appear as well. Does this work for you?

**Comment by Lexanius** [comment]
Yes it work. It was info. Never used this option before.
