### ISSUE TITLE
Introduction of LogLevel.Off

### ISSUE THREAD

**Issue by mspoerer** [mreuvers/typescript-logging#109]
Based on the log4J implementation, I would like to promote the additional log levels to expand the logger with missing functionality.

https://logging.apache.org/log4j/2.x/manual/customloglevels.html

The loglevel "off" is important because it completely disables logging, which can be useful in cases where logging is not needed or desired.

**Comment by mreuvers** [comment]
Hi there, thank you for the idea.

Adding an "off" sounds reasonable. I am currently swamped in other work, but I hope to pick this up sometime next week and have a proper look.

If implemented - I'll let you know, once a release with it has been made.

**Comment by mreuvers** [comment]
Version 2.1.0 has been released with LogLevel.Off added. Please make sure to update both core and your flavor to 2.1.0.
