### ISSUE TITLE
doLog doesn't seem to be called

### ISSUE THREAD

**Issue by madCoder24** [mreuvers/typescript-logging#11]
I have implemented a custom logger that logs to a file but the method doLog() doesn't appear to ever be called. Is there an issue with how I implemented the custom logging class? Any advice offered would be greatly appreciated.

If I log from within the constructor of the custom logger class it will write to the file just fine. So it seems like the issue is with doLog().

typescript-logging: 0.3.1
typescript: 2.2.0

**Logger Config**
```
import {
    Category, RuntimeSettings, CategoryDefaultConfiguration, LogLevel, LoggerType,
    CategoryLogFormat, CategoryServiceFactory, CategoryLogger
} from 'typescript-logging';

import { CustomLoggerImpl } from './MadLinkLoggerImpl';

export const catRoot = new Category('logger');

// Create options instance and specify 2 LogGroupRules:
// * One for any logger with a name starting with model, to log on debug
// * The second one for anything else to log on info
const config = new CategoryDefaultConfiguration(
    LogLevel.Debug, LoggerType.Custom, new CategoryLogFormat(),
    (root: Category, runtimeSettings: RuntimeSettings) => new CustomLoggerImpl(root, runtimeSettings)
);

// Create a named loggerfactory and pass in the options and export the factory.
// Named is since version 0.2.+ (it's recommended for future usage)
CategoryServiceFactory.setDefaultConfiguration(config);
export const logger: CategoryLogger = CategoryServiceFactory.getLogger(catRoot);
```

**Custom Logger Class**
```
import * as os from 'os';
import * as electron from 'electron';
import * as fs from 'fs';

import { LogGroupRule, AbstractCategoryLogger, Category, RuntimeSettings, CategoryLogMessage } from 'typescript-logging';

export class CustomLoggerImpl extends AbstractCategoryLogger {
    private fileLocation;

    constructor(rootCategory: Category, runtimeSettings: RuntimeSettings) {
        super(rootCategory, runtimeSettings);

        if (electron.remote.process.platform === 'win32') {
            this.fileLocation = electron.remote.process.env.LOCALAPPDATA + '\\MadLink\\ui-log.txt';
        } else {
            this.fileLocation = '/tmp/ui-log.txt';
        }
    }

    protected doLog(msg: CategoryLogMessage): void {
        fs.appendFileSync(this.fileLocation, this.createDefaultLogMessage(msg) + os.EOL);
    }
}
```

**Comment by mreuvers** [comment]
Hello @madCoder24 

For what I can tell based on your code on first glance, it looks fine. So it's odd if doLog(..) isn't called.

* Can you try logging on console or even throw an Error to see it doesn't get there ever? 
* Your settings are set to log on debug by default, on what level(s) are you trying to log?
* Are you using the lambda variant (those ending in 'c' e.g. errorc) to log? Maybe you could show me a few of the log statements that should be logged, but aren't?

Thanks!

**Comment by madCoder24** [comment]
Logging on console works just fine for me.

I am logging on debug.

This is one of my logging statements and the rest aren't any different other than the message.
`logger.debug('testing the logger');`

I will give you a link to the sample app that I am currently working with for this project. If there is anything else that I can answer. Please let me know. I am working in Angular with Electron underneath and I am also using the angular-cli for project generation and configuration. I don't know if that will help you at all, but that is what my project currently is using.

https://github.com/madCoder24/sample-app

**Comment by mreuvers** [comment]
Hello @madCoder24

I tried to use the app but ng build gives errors. Tonight after work I have a bit more time to look. Can you maybe tell me exactly what to do, to build and finally what to do in the app to trigger the logging? 

Thanks.

**Comment by madCoder24** [comment]
I cut the repo way down for you. So download it again and run "npm install" and then run "node_modules/.bin/electron-angular-toolkit build" then run "node_modules/.bin/electron .". You should be able to run "ng build" as well, but I have been using electron-angular-toolkit for my build purposes. It is possible that this use case isn't supported at all since the angular CLI doesn't technically support Electron projects. To trigger the logging just run the app and you should see a log in the appdata/local/MadLink folder. It should build for you successfully this time.

Thanks for the assistance.

**Comment by mreuvers** [comment]
Thanks I got some further this time but not as far as hoped.

Did clone, npm install and that went fine. The separate commands did not work unfortunately, it was looking for "ng" in my path which I don't have (it's only in node_modules).

Instead tried to use: 'npm run build' and that worked. Followed by 'npm run start' and that worked too (started server). When I opened the address in the browser, I got a "loading..." page and in the console it spit out:
`
ReferenceError: require is not defined[Learn More]  main.bundle.js:267:1
	[279] http://localhost:4200/main.bundle.js:267:1
	__webpack_require__ http://localhost:4200/inline.bundle.js:53:12
	<anonymous> http://localhost:4200/vendor.bundle.js:33353:11
	<anonymous> http://localhost:4200/vendor.bundle.js:33352:29
	__webpack_require__ http://localhost:4200/inline.bundle.js:53:12
	[282] http://localhost:4200/main.bundle.js:274:1
	__webpack_require__ http://localhost:4200/inline.bundle.js:53:12
	webpackJsonpCallback http://localhost:4200/inline.bundle.js:24:23
	<anonymous> http://localhost:4200/main.bundle.js:1:1
`

Where webpack was requiring 'url' it looked like.

Any idea or are we just unlucky, just as reference I run in linux - with no things installed globally (well except nodejs with npm).

**Comment by madCoder24** [comment]
I pushed a change to the repository to add another script to the package.json file.

So, in essence, add the following to the package.json file.

> "electron": "node_modules/.bin/electron ."

Run that command after "npm run build". This will bring up an electron app and it should write a text file to /tmp/ui-log.txt

**Comment by mreuvers** [comment]
That works and pops up the browser (firefox in my case). The console however has an error in the vendor.js, it seems to be unhappy with fs.existsSync
```
Uncaught TypeError: fs.existsSync is not a function
    at Object.<anonymous> (vendor.bundle.js:65271)
    at Object.<anonymous> (vendor.bundle.js:65277)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.104 (main.bundle.js:91)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.105 (main.bundle.js:141)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.102 (main.bundle.js:8)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.103 (main.bundle.js:48)
```
From the vendor bundle to give some context it was here:
```
/* WEBPACK VAR INJECTION */(function(__dirname) {var fs = __webpack_require__(74)
var path = __webpack_require__(164)

var pathFile = path.join(__dirname, 'path.txt')

if (fs.existsSync(pathFile)) {
  module.exports = path.join(__dirname, fs.readFileSync(pathFile, 'utf-8'))
} else {
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
}
```

**Comment by madCoder24** [comment]
Really? That happens even when you run "npm run electron"? It should create an electron window and shouldn't pop up a browser. 

Before we go any further let me run this project in Linux just so that we are in the same environment. I won't be able to do that until later today. I will get back to you.

**Comment by mreuvers** [comment]
It is not firefox (sorry didn't know what it was supposed to show), it is a window without address bar and all that, and a minimum menu bar. So I guess it's the thing you expect. :) The text in it says "Loading..." 
I did a control+shift+i to see the console (which is why I thought it was firefox, it probably uses it partially).

```
var fs = require('fs')
var path = require('path')

var pathFile = path.join(__dirname, 'path.txt')

if (fs.existsSync(pathFile)) {
  module.exports = path.join(__dirname, fs.readFileSync(pathFile, 'utf-8'))
} else {
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
}
```
Anyway, I debugged through the code above and the require('fs') thing does not properly load it seems, it seems like an ordinary object is returned just: { }, while the require('path') loads properly, it contains things in the object e.g. { delimiter: ":"  } (and a lot more). 
So that it fails in the code on that fs.existsSync makes sense as that function is not present at all.

Hope this helps a bit more.

**Comment by madCoder24** [comment]
No worries. I wasn't the clearest in what to expect when running the program. So I tried this repo in a Linux environment and I don't have that error. 
I want to double check what commands you are running.

I ran "npm install" then "node_modules/.bin/electron-angular-toolkit" which will build the application. It seems that "ng build" doesn't package things together correctly. I have had better luck with electron-angular-toolkit. So run "node_modules/.bin/electron-angular-toolkit" and let me know your results.

**Comment by mreuvers** [comment]
Unfortunately that does not work for me.

The command: "node_modules/.bin/electron-angular-toolkit build" fails (see below), it expects 'ng' to be in my normal shell path which I don't have (you maybe do?). I tried "node_modules/.bin/electron-angular-toolkit prepare" first as well, that works, followed by "node_modules/.bin/electron-angular-toolkit build" but that still gives the same error.

```
ng build failed
ng build --watch=false --output-path=bundle
Command failed: ng build --watch=false --output-path=bundle
/bin/sh: ng: command not found
```

**Comment by madCoder24** [comment]
It is up to you if you want to install ng globally. I have it installed globally on my system. I am prepared to walk away from this issue not because of the library, but because the angular CLI just isn't ready for this type of project. There just isn't much control allowed over the underlying webpack configuration and my running theory is that something is or isn't getting bundled correctly. 

On a side note to install "ng" globally just run "npm install -g @angular/cli". That should have installed it globally and then run the previously mentioned "node_modules/.bin/electron-angular-toolkit build" command.

**Comment by mreuvers** [comment]
Hello @madCoder24 

I got it running at last! :) I just put the ./node_modules/.bin/ng on the path temporally so it was happy now.

The app actually launched correctly now as well. I did debug the log code now and noticed that the level of the root category was not changed, so that ended up in not logging (it still thought it was error so skipped).

That made me look again to your code and then it struck me. 
You create the category before you modify the configuration and by default it does not reset existing categories/loggers (so that one was still set to "Error" which is the default). Now it logged for me in the file as expected.

Easiest fix is to move it like this:
```
const config = new CategoryDefaultConfiguration(
    LogLevel.Debug, LoggerType.Custom, new CategoryLogFormat(),
    (root: Category, runtimeSettings: RuntimeSettings) => new CustomLoggerImpl(root, runtimeSettings)
);
CategoryServiceFactory.setDefaultConfiguration(config);
export const catRoot = new Category('logger');
export const logger: CategoryLogger = CategoryServiceFactory.getLogger(catRoot);
```
Or use:
```
CategoryServiceFactory.setDefaultConfiguration(config, true);
```
That will reset all categories/loggers to use the new settings.

What do you think, maybe the flag should be true by default as it caused a lot of confusion?

So this electron thing does work for me too now. Why isn't the angular-cli not ok/ready btw (merely curious here)?

I hope this works for you too.

**Comment by madCoder24** [comment]
You, sir, are a genius! I never noticed that issue. It now logs to the file beautifully. I am on the fence about making that flag true by default. I always lean toward having booleans default to "false" especially when dealing with settings. If the user wants it to be true then they can set it to true. My case it just a one off case and I would make any changes to the code.

Well in normal Webpack development you can specify a target like "electron-renderer". This allows you to target specific things like node, electron, etc. If I was to use the target "node" then it wouldn't touch native modules like 'fs' or 'path'. But from what I know you cannot do that in the Angular CLI as of now according to this [issue](https://github.com/angular/angular-cli/issues/4227#issuecomment-275548444). I love the CLI and I think it makes things Angular much easier to use but there are still specific cases where it seems to fall short like Electron. Now that isn't to say it isn't possible to use the CLI with Electron like I am in that sample app. But, this is also why I brought in the package electron-angular-toolkit. 

Anyways enough of my rant about Angular. I really appreciate your help on this issue! :) If I ever get some more time, I would love to help contribute to this project.

**Comment by mreuvers** [comment]
You're welcome! Glad it works now. :)
Thanks for the quick explanation btw.

I will change this flag to true by default for the 0.4 release, it will just be less confusing. I have created issue #12 for this. If you're fine with it, you can close this bug.

If you do have some time some day in the future feel free to poke me, and see if there's stuff to be done by then. :)

**Comment by madCoder24** [comment]
Yes, I am closing this issue as it is fixed. Thanks again!
