### ISSUE TITLE
Multiple custom logger category example

### ISSUE THREAD

**Issue by madCoder24** [mreuvers/typescript-logging#13]
I don't have an issue with anything just mainly looking for advice or thoughts on this implementation using this library. What would it look like if I wanted multiple categories that had two different custom logging implementations? Would it be better to determine the category that is being logged in one custom class and forward the message to the appropriate file? 

My use case is that I want one log file for debugging and another file that contains system information like hostname, architecture, CPUs, and other statistics. What would be the best way to implement this case using this library?

Thanks for any advice.

**Comment by mreuvers** [comment]
Hello @madCoder24 

Questions are always welcome. :)

You can specify one custom logger callback (to create custom loggers), so if you want to log in two different distinct ways, I suggest to return two distinct custom loggers. 

Create two root categories (and child categories for them if needed). 
Then set the default configuration with LoggerType.Custom, and specify a lambda function for creating a custom logger (see the example in the docs).
The function is called if a logger for a root category must be created (only once normally for each root category). Based on either of the two root categories you created, you can decide what custom logger to return, with each of them logging to a different file.

Does this make sense?

**Comment by madCoder24** [comment]
It sort of does... my attempt is below. I feel like I need to call `setDefaultConfiguration()` but that would override the secondary logger, correct?

```
import { SystemLogger } from './system.logger';
import {
    Category, RuntimeSettings, CategoryDefaultConfiguration, LogLevel, LoggerType,
    CategoryLogFormat, CategoryServiceFactory, CategoryLogger
} from 'typescript-logging';
import { MadLinkLogger } from 'app/logger/madlink.logger';

// Create options instance and specify 2 LogGroupRules:
// * One for any logger with a name starting with model, to log on debug
// * The second one for anything else to log on info
const config = new CategoryDefaultConfiguration(
    LogLevel.Debug, LoggerType.Custom, new CategoryLogFormat(),
    (root: Category, runtimeSettings: RuntimeSettings) => new MadLinkLogger(root, runtimeSettings)
);

const systemLogConfig = new CategoryDefaultConfiguration(
    LogLevel.Debug, LoggerType.Custom, new CategoryLogFormat(),
    (root: Category, runtimeSettings: RuntimeSettings) => new SystemLogger(root, runtimeSettings)
);

// CategoryServiceFactory.setDefaultConfiguration(config);
export const catRoot = new Category('logger');
export const catSystem = new Category('system');

CategoryServiceFactory.setConfigurationCategory(config, catRoot);
CategoryServiceFactory.setConfigurationCategory(systemLogConfig, catSystem);

export const logger: CategoryLogger = CategoryServiceFactory.getLogger(catRoot);
export const systemLogger: CategoryLogger = CategoryServiceFactory.getLogger(catSystem);

```

**Comment by mreuvers** [comment]
@madCoder24 

I think your code should work, you can set the configuration for each category that way.
A different way could be roughly like this  (writing this from head, so apologies if it won't compile):
```
import { SystemLogger } from './system.logger';
import {
    Category, RuntimeSettings, CategoryDefaultConfiguration, LogLevel, LoggerType,
    CategoryLogFormat, CategoryServiceFactory, CategoryLogger
} from 'typescript-logging';
import { MadLinkLogger } from 'app/logger/madlink.logger';

export const catRoot = new Category('logger');
export const catSystem = new Category('system');

// Define the lambda separately so you have more control (you could inline it below too, whatever you prefer)
const customLoggerFunction =  (root: Category, runtimeSettings: RuntimeSettings) => {
  if (root === catRoot) {
    return new MadLinkLogger(root, runtimeSettings)
  }
  return new SystemLogger(root, runtimeSettings);
};
const config = new CategoryDefaultConfiguration(
    LogLevel.Debug, LoggerType.Custom, new CategoryLogFormat(), customLoggerFunction
);
CategoryServiceFactory.setConfigurationCategory(config, true);
```

This sets one custom logger for all categories, based on the root you return the appropriate logger.

**Comment by madCoder24** [comment]
Excellent! Your implementation proved successful. Thanks again for your assistance. You can go ahead and close this.

**Comment by mreuvers** [comment]
You're welcome! Closing the issue now then.
