### ISSUE TITLE
Logger methods should allow additional informations

### ISSUE THREAD

**Issue by CSchulz** [mreuvers/typescript-logging#14]
The passed in information can be used to created some own message strings or for using it to send it to a server or similar overwriting the doLog method.

```
this.logger.info({msg: 'User 1 logged in', user: 1});

doLog(message: LogMessage) {
  message.getAttributes().user
}
```

**Comment by mreuvers** [comment]
Hello @CSchulz 

Thank you for your suggestion. I will consider something like this, I will plan it in for after the 0.4 release.

**Comment by CSchulz** [comment]
If you have some ideas how to implement it correctly, I will create a PR.

**Comment by mreuvers** [comment]
Hello before spending time, it may be better to roughly explain first what you like to do. Without this, I cannot say whether it fits the library and has a chance to be accepted.

**Comment by mreuvers** [comment]
Oh seems our comments crossed I was responding on your previous edit.

**Comment by mreuvers** [comment]
I don't have time right now but will get back to this tomorrow. If you have an idea feel free to write it down already.

**Comment by mreuvers** [comment]
Hey @CSchulz 

I have given it some thoughts, for now I see two possible ways of doing it. Since I'd prefer not to break the existing api.

In this example I use the CategoryLogger, but in the end, if added it needs to apply to both category style and log4j like style loggers.

We could extend the existing CategoryLogger like this for example:
```
// Introduce new interface
export interface LogData {

  message: string;
  data?: any;

  // If not given, standard stringify must be used by standard loggers, if given uses this function.
  ds?(data: any): string;
}

// On CategoryLogger (example with trace one), basically you get a choice string or LogData.
trace(msg: string | LogData, ...categories: Category[]): void;
// etc.

// Possible usage:
const someAwesomeObject = { name : "User" };
this.trace({message: "hello", data: someAwesomeObject, ds: (data: any) => {return JSON.stringify(data); } });
```

Another way is to add a new interface say CategoryLogger2 (for lack of a better name), note the additional "error" attribute:
```
export interface LogData {
  message: string;
  error?: Error;
  data?: any;

  // If not given, standard stringify must be used by standard loggers, if given uses this function.
  ds?(data: any): string;
}

export interface CategoryLogger2 {
  trace(logData: LogData, ...categories: Category)
 //  etc. mimics CategoryLogger
}

// Again for lack of a better name, would return this one.
CategoryService.getRootLogger2(..)
```
Both solutions would require CategoryLogMessage to have additional attributes present (the data and stringify function, both as optional). Then in doLog(..) all loggers will have access to it as well.

The second solution requires a lot of more work, as AbstractCategoryLogger cannot implement the second interface and basically all existing end user code could break and I suspect cause API breaks all over the place too.

My preference for now would be the first solution.

These are my first thoughts, what do you think?

**Comment by CSchulz** [comment]
In general I prefer the first solution as well, because it allows the simple usage with just a string message. I think there are a lot of cases, where no further data is required and always creating an object would be too much.

**Comment by mreuvers** [comment]
Sorry for the delay.

So the first solution it is then. It will have to apply to both style of loggers (category and log4j like ones). 
Do you still want to do this?

**Comment by CSchulz** [comment]
Would be no problem for me.

**Comment by mreuvers** [comment]
Ok, thanks! In that case go ahead. :)

If you have any questions or run into other things while you work at this, don't hesitate to ask. Don't forget to add a few additional tests for this.

If you want to know if all is fine once you're done, use "npm run release" which will build and run everything.

Good luck!

**Comment by CSchulz** [comment]
Who should call the ds method?

I have noticed a difference between log message implementations regarding the way of accessing the attributes. getter/setter vs. methods.

**Comment by mreuvers** [comment]
The ds should be called by the ConsoleLoggerImpl/MessageBufferImpls (one for each log4j/category style). I think appending it behind the normal formatted message should be ok. 
If ds is undefined, use standard JSON.stringify(..) instead. This way the data is always appended by non custom loggers at least.

Yeah attributes vs methods on the LogMessage/CategoryMessage right?
I changed that over time and I am still not sure which one I prefer. Do you have a preference? In the end they both do the same.

**Comment by CSchulz** [comment]
I think it makes more sense when the MessageUtils would add them because both are calling `MessageFormatUtils.renderDefaultLog4jMessage(msg, true)` via AbstractLogger.

I have no real preference either but I think make them consistent and remove the setter would be good.

**Comment by mreuvers** [comment]
Agreed MessageFormatUtis would be a good place to put it.

For now just leave the messages getters/setteds as they are. I will deal with them separately soon.

**Comment by mreuvers** [comment]
Thanks for the pull request. Could you please add some tests using the LogData to proof it works and remains working? With and without the 'ds' function present e.g. 
They can be added to the existing spec files.

**Comment by CSchulz** [comment]
I will update it soon. It was my first draft to see if you are okay with the direction.

**Comment by mreuvers** [comment]
All right, but yes on first glance over the changes it's going in the right direction I think.

**Comment by CSchulz** [comment]
Updated PR.

**Comment by mreuvers** [comment]
Thank you. It's complete now? Then I will try make a release upcoming weekend.

**Comment by CSchulz** [comment]
Should be completed.

**Comment by mreuvers** [comment]
I've merged your pull request (with some small changes based on code review), thanks for doing this @CSchulz !

I reopened this issue as I may want to add some doc update later on.

I will release soon, but not until it's ready. There's a few things I want to do/add to this release (unrelated to this issue). 

Thanks again.

**Comment by mreuvers** [comment]
Reopen as said.

**Comment by mreuvers** [comment]
Resolved and released.
