### ISSUE TITLE
Installation Error - possibly not compatible with recent versions of npm?

### ISSUE THREAD

**Issue by austinthemassive** [mreuvers/typescript-logging#18]
`npm install --save typescript-logging` results in an error titled 

> Cannot read property '0' of undefined

I dug into the associated log file, but it doesn't have much of interest other than the node and npm version numbers.

> 3371 verbose node v8.2.1
> 3372 verbose npm  v5.3.0
> 3373 error Cannot read property '0' of undefined

**Comment by mreuvers** [comment]
Hello @austinthemassive 

It is likely related to this bug in npm: npm/npm#17858 

Could you try install an older npm version for example using: npm install -g npm@5.2.0 (it seems it's not resolved in 5.3.0 and 5.4.0 either), and let me know if this works?

Thank you!

**Comment by austinthemassive** [comment]
That seems to have been the issue. Seems to be working just fine!
