### ISSUE TITLE
log.debug text not displayed in node 8 console

### ISSUE THREAD

**Issue by emilianosantucci** [mreuvers/typescript-logging#19]
Hi @mreuvers,
I'm trying to write messages with log level **debug** but I can't see it on CLI.

Configuration:
```ts
CategoryServiceFactory.setDefaultConfiguration(new CategoryDefaultConfiguration(LogLevel.Debug));

export const appLog: Category = new Category('myApp');
export const log: CategoryLogger = CategoryServiceFactory.getLogger(appLog);

log.debug('I see it!!!');
```
Expected:
```log
2017-09-15 19:14:13,286 DEBUG [myApp] I see it!!! 
```
Actual:
```log
```

Version: **0.4.0**

Is it a bug or I'm doing something wrong?

**Comment by mreuvers** [comment]
Hello @emilianosantucci 

Yeah normally that should work. Where are you doing this? If you use the chrome console it may be that filtering is not set to verbose? That is actually something I am considering to change, to always log to the standard log level instead - to prevent the confusion. 

If you use chrome you can also use: https://github.com/mreuvers/typescript-logging-extension or for any browser: check out https://github.com/mreuvers/typescript-logging/blob/master/docs/latest_console_control.md which allows control of the log levels from the CLI (and can also show you the current levels).

Let me know if any of this works. Thanks.

**Comment by emilianosantucci** [comment]
HI @mreuvers,
thank you for your reply.

I'm using it on a backend project written in NodeJS + TypeScript.
I've tried several approachs but the level reached by log never scale down to WARN.

Only for troubleshooting purpose, I've try to print out the runtime settings with this command:
```ts 
CategoryServiceFactory.getRuntimeSettings()
```
Obtain this: 
```log
app_1  |    CategoryDefaultConfiguration {
app_1  |      _formatterLogMessage: null,
app_1  |      _logLevel: 1,
app_1  |      _loggerType: 0,
app_1  |      _logFormat: 
app_1  |       CategoryLogFormat {
app_1  |         _dateFormat: [Object],
app_1  |         _showTimeStamp: true,
app_1  |         _showCategoryName: true },
app_1  |      _callBackLogger: null },
app_1  |   _rootCategories: 
app_1  |    [ Category {
app_1  |        _children: [],
app_1  |        _logLevel: 4,
app_1  |        _id: 1,
app_1  |        _name: 'registry/host-registry',
app_1  |        _parent: null } ],
app_1  |   _categoryRuntimeSettings: SimpleMap { array: { 'registry/host-registry': [Object] } },
app_1  |   _categoryOriginalRuntimeSettings: SimpleMap { array: { 'registry/host-registry': [Object] } },
app_1  |   _rootLoggers: SimpleMap { array: { 'registry/host-registry': [Object] } } }
```
As show above, the default log level seems to be the right one (1 = Debug) but I notice the log level on my root category with different level (4 = Error) even I never setting it (I think is the default one). I also notice that there is not configurable during category instantation (`new Category(...)`).

Any  suggestion?

**Comment by mreuvers** [comment]
Hello @emilianosantucci 

On first sight it looks ok. As workaround can you try setting the default category settings - after creating the category and logger?

If that does not help can you try the console control I mentioned in the previous comment that should work for node too, and print the settings. It could very well be you ran into a bug.

**Comment by mreuvers** [comment]
Hello @emilianosantucci 

Sorry for the delay but I was on holiday previously hence I couldn't properly look at it.

I have not been able to reproduce this myself so far, could you perhaps make a minimum testcase (maybe dump it in a repository so I can just clone and see)?

Thanks!

**Comment by ezequiel-umu** [comment]
@mreuvers I happens to me when using Node version 8, but it works when using Node version 7. 
If you still can not reproduce I can add more information.

**Comment by mreuvers** [comment]
Hello @ezequiel-umu 

Thank you for the heads up. I am normally running and testing against an LTS version of Node. I tested it on 8 now, and indeed it does not log. It seems node 8 has changed some things around it's console.

console.debug now exists, but does not print anything (the behavior you see), at older versions it does not exist and falls back to console.log instead (hence you see the logging in 7 e.g.).

I am going to change this back to console.log, as there's too much difference between all node and browser consoles. That way it will be visible at least everywhere.

Expect a release shortly to fix this.

**Comment by mreuvers** [comment]
Hello @ezequiel-umu  0.4.1 has been released, if you still encounter issues please let me know.

**Comment by emilianosantucci** [comment]
Hi @mreuvers,
sorry for my late on response but I beeb busy on other projects.

Thanks for new release, I try that asap.
