### ISSUE TITLE
how do I prefix each message, from a named logger with it's name ? 

### ISSUE THREAD

**Issue by HNeukermans** [mreuvers/typescript-logging#2]
desired scenario:

//create a named logger.
var logger = LFService.createLoggerFactory().getLogger('chatbox');

//write a message to the log. The name of the logger is prefixed.
logger.info('started') => should output 'chatbox: started';  

Does your library support this kind of scenario ? If not, can I solve it with a customlogger? How then?

**Comment by mreuvers** [comment]
Hello, by default the name is already present (prefixed). In your example the log statement will look similar to: 

`2016-12-20 17:44:26,216 INFO [chatbox] started`

**Comment by HNeukermans** [comment]
Nice on. Maybe you can add it to the readme documentation?

**Comment by mreuvers** [comment]
Good idea, I will leave this issue open to track. Within a few weeks from now I hope to release a new version and will add it.

**Comment by mreuvers** [comment]
A new release has been made a few days ago, and the documentation now also shows an example of the logging. Feel free to check it out, there's a chrome developer extension now too.

Closing this issue. :)
