### ISSUE TITLE
Logging to File

### ISSUE THREAD

**Issue by iceslove** [mreuvers/typescript-logging#20]
How to configure the log logger for a file

**Comment by mreuvers** [comment]
Hello @iceslove 

You can use a custom logger (see the documentation), which will write to a file. How to write to a file, please check out the nodejs documentation.

**Comment by mreuvers** [comment]
Assuming you resolved your problem.

**Comment by shwetaaher** [comment]
> Hello @iceslove
> 
> You can use a custom logger (see the documentation), which will write to a file. How to write to a file, please check out the nodejs documentation.

Hi, Can you please provide the documentation link?
