### ISSUE TITLE
Failed at the typescript-logging@0.1.3 postinstall script 'typings install'.

### ISSUE THREAD

**Issue by darilin** [mreuvers/typescript-logging#23]
Failed when I run npm install. I tried npm cache clean, deleted folder node_moduls... nothing works for now

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! typescript-logging@0.1.3 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-logging@0.1.3 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typescript-logging package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript-logging
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typescript-logging
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\TSF_DEV\Development\Player\npm-debug.log

**Comment by mreuvers** [comment]
Hello @darilin 

You are installing a very old typescript-logging version, that version used to install typings in it's 'post-install' step and this will now cause issues depending on typescript version etc.

That step is not necessary anymore with later typescript-logging versions. Please upgrade to the latest and greatest version available (currently 0.4.2).

**Comment by mreuvers** [comment]
Closing issue, assuming you resolved it.
