### ISSUE TITLE
Library support - static default logger factory

### ISSUE THREAD

**Issue by IsNull** [mreuvers/typescript-logging#29]
I would be interested to use this logger in several libraries and have the ability to configure it globally (i.e. in the consuming app).

For this, a global exported logger-factory is not going to work. I wonder if instead a global static default logger factory or factory manager would make sense. This way, the logs of all libraries and the main app can be configured from the main app.

Something along the line like these static functions:

```typescript
export class LoggerManager {
   public static readonly Default = new LoggerFactoryImpl();

   public static getLogger(named: string): Logger {
      return LoggerManager.Default.getLogger(named);
   }
}
```

Allowing to access the logger:

```typescript
class MyClass {
    private readonly logger = LoggerManager.getLogger('MyClass');
}
```

What do you think?

**Comment by mreuvers** [comment]
Hello @IsNull 

Could you elaborate a bit more? 

For what I understand you'd like something centrally to be available for the log4j style of logging, that you can reconfigure/change from a main app. The libraries you talk about are used by this consuming app (so they are dependencies in package.json themselves)?

**Comment by IsNull** [comment]
Hi there,

The idea is basically to have a common logging 'experience', no matter if the main app is logging or a library. This obviously requires that all libraries and the main app use the same logging interface, and more specifically, the same logger-factory with the same options. This is what log4j basically gives you in the Java world, simply because it is used by most libraries / projects and the default way is to use the static logger builder (which is configured once in the main app).

Now, I can't force any other typescript project / library to use this (or any other) logging interface - most of them don't even bother anyway and log directly to the console - if they log at all.
But since we already have a number of libraries ourselves, we could at least have a common logging library in our ranks. 

However, with your library i don't see any other way than configure the logger factory in each project / library separately, and I won't be able to configure the logs of our libraries from our main app.

In the long run - if this library becomes a pseudo standard for logging in ts - it would allow to configure all libraries which support it in the consuming app.

I hope this clarifies things. 😄

**Comment by mreuvers** [comment]
Yup thanks this is clear. :)

It makes sense, for the log4j variant to at least have one generally available so if you want, that you can use it. If you don't want to, you don't have to after all. I will consider to make this an enhancement.

For the category variant of logging you already can do what you want I think without any changes
Since you can just specify a Category (or more) in your libraries and use these directly for logging, they will become available automatically if your main app starts using such a library (and you can do the config in the main app if needed). Curious if you looked at this already?

**Comment by IsNull** [comment]
Thanks for the hint to the category style logging. It could partially work, but we had to ensure there is never a duplicate category registered.

If I understand correctly the usage would be:

**library-a-config.ts**
```typescript
export const libraryA = new Category("library-a");
export const productLogger = new Category("product", libraryA);
```

**library-b-config.ts**
```typescript
export const libraryB = new Category("library-b");
export const productLogger = new Category("product", libraryB); // In case both libraries had products
```

**main-app-config.ts**
```typescript
export const myApp = new Category("myapp");
export const productLogger = new Category("product", myApp); // In case the main app had also product domain

// And config all the loggers
CategoryServiceFactory.setDefaultConfiguration(new CategoryConfiguration(LogLevel.Info));
```
This way it could work.

**Comment by IsNull** [comment]
Have a look at this PR #30. I have used the existing LoggerFactory and added the global static default factory methods.

**Comment by mreuvers** [comment]
Yeah the category code you sketched above should work. If you got control over the libraries that should be fine otherwise it may lead to issues.

Thanks for the PR, I'll have a look at it later (short on time atm and I don't want to rush this). In any case I will create an enhancement bug later for this so it will be dealt with in the next 0.6.0 release.

**Comment by mreuvers** [comment]
FYI: Created issue #31 to track this, will leave this issue open until that one is resolved.

**Comment by mreuvers** [comment]
See issue #31, a default loggerfactory has been made available  at last(see the docs in log4j for details). Version 0.6.0 was released containing this. 

I will close this issue in a couple of days from now, in case you have some remarks.

**Comment by mreuvers** [comment]
Closing issue, it was resolved.
