### ISSUE TITLE
Export LogData

### ISSUE THREAD

**Issue by skocks** [mreuvers/typescript-logging#34]
To be able to implement a custom logger, without inheriting from AbstractCategoryLogger or AbstractLogger, LogData has to be exported from the library.

**Comment by mreuvers** [comment]
Thank you for the issue report and thanks for the pull request. I will merge and release a patch version Monday/Tuesday.

**Comment by mreuvers** [comment]
Merged your pull request into master (commit e7096b7), and released 0.6.1 on npm.
