### ISSUE TITLE
React-native app crashes: "window.removeEventListener" is not a function

### ISSUE THREAD

**Issue by maudnals** [mreuvers/typescript-logging#43]
We have a react native app, created with `react-native init`. 
Importing typescript-logging makes the app crash.
**This issue didn't come up in a project using react-native 0.59.**

* react-native version: 0.61.2.
* typescript-logging version: 0.6.3

Steps to reproduce:

* Create a new react native project with `react-native init` (see https://facebook.github.io/react-native/docs/getting-started > tab "React native")
* Launch the app: `yarn start` in one terminal tab and `react-native run-ios` in another
* Add "typescript-logging": "^0.6.3" into `package.json` and run `yarn`
* Add `import logger from 'typescript-logging'` into App.js
* The app crashes (see screenshot)

Thanks in advance for your help!! 🚀  @mreuvers 

<img width="423" alt="Screenshot 2019-10-11 at 11 17 12" src="https://user-images.githubusercontent.com/9762897/66640592-874fc400-ec19-11e9-8c8c-066c492cffbb.png">

**Comment by mreuvers** [comment]
Hello @maudnals ,

Thank you for reporting the issue. My guess is that you used to have something in your project that poly-filled various methods (such as the one now failing on the window object). Maybe due to the upgrade of react-native, or something else you upgraded/dropped in your project?

In any case where it currently fails is not even relevant for a native app (it's related to the extensionpoint for chrome and you can't use that anyway).

I intend to fix this, would you be willing to test this later once fixed on a branch? I am unable to test it myself as I run linux and can't test on ios.

**Comment by maudnals** [comment]
Hello @mreuvers,

Thank you for your swift reply. 
Happy to test the fix later on! 

I've set up an example app where the issue happens, so you can see my exact setup if that helps: https://github.com/maudnals/react-native-logger-test/tree/master

This example app has been created following the steps mentioned above (https://github.com/mreuvers/typescript-logging/issues/43#issue-505740796): simply create a react native app and add typescript-logging as a dependency.

Let me know if I can help in any way.

**Comment by mreuvers** [comment]
Probably not then, unless they shipped a poly-fill previously in an older version?
In any case, let's try fix it. :)

I will let you know when a branch with hopefully the fix is available for you to test (it may be a few days). Thank you!

**Comment by maudnals** [comment]
Sure, thanks!

**Comment by mreuvers** [comment]
Hello @maudnals,

I have made the fix and hopefully it will work.

To test (yarn command should be similar I think?):

- clone this repository
- in the clone directory:
  - git checkout issue43
  - npm ci  (this one matters, it installs the dependencies from package-lock.json)
  - npm pack (this will create a 0.6.4 tgz file)
- in your test project directory: 
  - npm uninstall typescript-logging --save
  - check that it was removed: node_modules/typescript-logging (should be gone)
  - npm install path_to_0.6.4.tgz
  - do your usual build and run the test project and hopefully it works again

Let me know how things go and/or if you have questions. Thanks!

**Comment by maudnals** [comment]
Hi @mreuvers ,

Looking great! I've followed all the above steps and the app is running smoothly.
Thanks a ton for this fast fix 🎉 

I see the additional checks you've added on there. Out of curiosity, do you know where the problem originated from? Has React changed the way `window` polyfills are applied in the latest react-native?

**Comment by maudnals** [comment]
Hi @mreuvers,
Great, I've tested it, `0.6.4` in `package.json` works. Thanks! 
From my perspective this issue can be closed - I leave it up to you.
Cheers!

**Comment by mreuvers** [comment]
Hey @maudnals,

Sounds like things are fine now, I will close this issue. Thanks again for reporting and testing it out!
