### ISSUE TITLE
Shared Logger

### ISSUE THREAD

**Issue by fredfortier** [mreuvers/typescript-logging#52]
I have two TS applications with shared packages:
- A frontend bundled for the browser with react-scripts
- A nodejs backend

I'd like to move from console.log to log4j-style logging across both projects including the shared modules. Ideally, I would create a log package that determines the runtime context, and initialize the logger accordingly. Then, each module (node, frontend, or shared) would import the logger in the same manner:
```
import log from 'common-logger';
// This should just work because the logger is configured in the common-logger package
log.info('foo');
```
Is this a valid design and are there examples of such implementation with typescript-logging?

**Comment by mreuvers** [comment]
Hi there,

I am not sure I fully understand your question here, but assuming your shared module is used by both the frontend and backend.

You could put some config/setup in the shared module, e.g. something like this:

LogConfig.ts (in shared module)
```typescript
import { .... } from "typescript-logging"; // Relevant imports

const optionsBackend = new LoggerFactoryOptions()
.addLogGroupRule(new LogGroupRule(new RegExp("model.+"), LogLevel.Info))
.addLogGroupRule(new LogGroupRule(new RegExp(".+"), LogLevel.Info));

const optionsFrontend = new LoggerFactoryOptions()
.addLogGroupRule(new LogGroupRule(new RegExp("view.+"), LogLevel.Info))
.addLogGroupRule(new LogGroupRule(new RegExp(".+"), LogLevel.Info));

// You could of course make both configurations different depending on the needs of backend or frontend.
// E.g. like using a custom logger.
const factoryBackend = LFService.createNamedLoggerFactory("LoggerFactoryBackend", optionsBackend);
const factoryFrontend = LFService.createNamedLoggerFactory("LoggerFactoryFrontEnd", optionsFrontend);

export function getLogger(name: string) {
  // Node should not have window, so that is backend then.
  if (typeof window === "undefined") {
    return factoryBackend.getLogger(name);
  }
  return factoryFrontend.getLogger(name);
}
```
Make sure to export the logger function in your index.ts or so.

Elsewhere in your code you can just use the exported function getLogger("SomeName") and it should work for both frontend and backend provided your shared module is present of course.

**Comment by fredfortier** [comment]
That's exactly what I was looking for. Thanks!
