### ISSUE TITLE
Simple Pattern Layout

### ISSUE THREAD

**Issue by fredfortier** [mreuvers/typescript-logging#53]
log4js has a pattern layout feature: https://log4js-node.github.io/log4js-node/layouts.html I haven't seen an equivalency in the documentation. How is it done in here?

My requirement is very simple. I want to configure the logger print any object in terse format on a single line. Concretely, I want `log(myComplexObject)` to always behave like: `console.log(JSON.stringify(myComplexObject))` instead of `console.log(myComplexObject)` (which pretty prints the object including new lines).

**Comment by mreuvers** [comment]
Hey there,

No there are no formatting layouts. There's no real need for that if you use typescript. If you want to write your json objects away in some format you can easily use the template string in typescript like.

```typescript
log.debug(`This writes json on 1 line ${JSON.stringify(json)}`);
```

As alternative you could format your own message. E.g write the message away like this and checkout https://github.com/mreuvers/typescript-logging/blob/master/docs/latest_log4j.md#formatting-message
```
log.debug({msg: "This writes json on 1 line {}", data: json});
```
The LogMessage will then contain all data you may need to do whatever you want (such as replacement in the example above).

**Comment by fredfortier** [comment]
I was hoping to leave my messages as-is and just replace `console.log` by something else. Is there no way wrap a formatter around every `log.x` calls? Perhaps by overriding a particular function? Using `JSON.stringify` everywhere seems a bit too verbose.

In your opinion, what would be the most idiomatic approach?

1. Using a custom `formatterLogMessage` with the `log.debug({msg: "This writes json on 1 line {}", data: json});` syntax you suggested.
2. Using an independent custom formatter `log.debug(formatln("This writes json on 1 line", data));`.

The latter is easier to refactor into, but I'm asking your opinion because you must know a lot about what makes log messages easy to read and maintain. We do use typescript in our entire codebase.

**Comment by mreuvers** [comment]
Well logging needs differ from project to project in my opinion, so there is no 1 good way.

In large projects we often end up wrapping the logging library (doesn't matter which one is backing it).

This allows us to add some custom things to it what such library doesn't offer itself (whatever that may be, as that depends on the project). E.g. the "getLogger" example from your previous issue would be a nice place to wrap the logger with an instance of a custom class that implements a custom interface (e.g. your own, or one extending the current Logger interface).

This would also allow you to do the replacement in your custom class log(..) methods, before you log the message with the actual logger (in that case you could use {} with replacement for example and pass additional arguments to the methods).

This is not hard to make, you only need to implement 1 class with the minimum set of log methods you expect necessary, and when you return that class from getLogger(..),  you can just replace your console.log exactly like you wanted (log.debug(...)).
