### ISSUE TITLE
Error: LoggerFactory with name <NAME> already exists.

### ISSUE THREAD

**Issue by drewstone** [mreuvers/typescript-logging#60]
For some reason we've made no changes to our logger and in a feature branch this is coming up. I'm not sure how to debug as we're only creating the factory in one location throughout the repo.

**Comment by mreuvers** [comment]
Hey there,

That sounds odd. At the spot you are creating it, are you sure it is only ever called once as it sounds like it's called more than once. The most simple way to see this is to just log just before creation to the console to find out.

**Comment by mreuvers** [comment]
Closing this issue as it's very old, typescript logging 2 (major new version) has been released. Consider upgrading.
