### ISSUE TITLE
Parent category not shown in log message

### ISSUE THREAD

**Issue by Chris-Thompson-bnsf** [mreuvers/typescript-logging#63]
I am guessing that I've just configured something incorrectly, but based on examples and some cursory looks over the implementation code in the repo, I was expecting different output when I do the following:

```tsx
// src/logging/logging.ts
import * as TsLogging from 'typescript-logging';

const configuration = new TsLogging.CategoryConfiguration(
        TsLogging.LogLevel.Info,
);
configuration.logFormat.showCategoryName = true;
configuration.logFormat.dateFormat = new TsLogging.DateFormat(
	TsLogging.DateFormatEnum.YearDayMonthTime,
);

TsLogging.CategoryServiceFactory.setDefaultConfiguration(configuration);

export const rootLogger = new TsLogging.Category('root');

// src/App.tsx
import { rootLogger } from '../logging/logging';
import { Category } from 'typescript-logging';
import React, {useEffect} from 'react';

const logger = new Category('App', rootLogger);

const App: React.FC<{}> = (props) => {
	useEffect(() => {
		logger.trace(() => 'Root app rendered');
		logger.debug(() => 'Root app rendered');
		logger.info(() => 'Root app rendered');
		logger.warn(() => 'Root app rendered');
		logger.debug(() => ({
			msg: 'Data message 1',
			data: {
				someProp1: 'some-prop1',
				otherProp: 57,
				when: new Date(),
			},
		}));
	});

       return <div />;
}
```

Output in the browser's console:
2020-11-12 13:01:20 INFO [App] Root app rendered
react_devtools_backend.js:2430 2020-11-12 13:01:20 WARN [App] Root app rendered

The format I would have expected, based on having a child category, was that the `[Category]` would have looked something like `[root, App]`.

**Comment by mreuvers** [comment]
Hey there,

I can see why you would think this. But if you'd want to see more than the category name of the one you're logging with you'd have to log like:

```
logger.warn(() => 'Root app rendered', someOtherCategory, yetAnotherCategory);
```

Where the additional categories are added after the message. It's something we have not been completely happy with either over time. 

If you want to log as in your example, then I suggest you to add a custom message formatter on your configuration:
```
configuration.formatterLogMessage = (msg: CategoryLogMessage): string => {
  // Do your stuff here
};
```

That would allow you to format your message as you'd like, as you will have access to the category (and it's parent(s)). Be sure to also checkout `MessageFormatUtils` as it may help you to more easily format the raw message.

**Comment by Chris-Thompson-bnsf** [comment]
I was able to get this working in the expected way, and I was able to leverage some of the existing logic that is in `MessageFormatUtils`, but there is a piece I seemed to have to rewrite that might be nice to have exposed as a helper function (if it isn't already and I just didn't find it).

```ts
const getCategoryString = (category: Category): string => {
    const pieces: string[] = [category.name];
    let parent = category.parent;
    while (parent) {
        pieces.push(parent.name);
        parent = parent.parent;
    }
    return `[${pieces.reverse().join('|')}]`;
};

const getLogDataString = (logData: LogData | null): string => {
    if (!logData?.data) return '';

    if (logData.ds) return logData.ds(logData.data);

    return JSON.stringify(logData.data);
};

export const customFormatter = (msg: CategoryLogMessage): string => {
    const pieces: string[] = [
        msg.logFormat.showTimeStamp ? MessageFormatUtils.renderDate(msg.date, msg.logFormat.dateFormat) : '',
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        LogLevel[msg.level]!.toUpperCase(),
        ...(msg.logFormat.showCategoryName ? msg.categories.map(getCategoryString) : []),
        msg.messageAsString,
        getLogDataString(msg.logData),
    ];

    return pieces.join(' ');
};
```

Specifically, the `getLogDataString` part was written based on the existing behavior - as I didn't want to change that part of the log format.
