### ISSUE TITLE
Remove "Dropping unknown message"

### ISSUE THREAD

**Issue by mreuvers** [mreuvers/typescript-logging#8]
As reported and fixed in pull request by @TobiasWalle to drop the unnecessary logging of "Dropping unknown message". This message is really only relevant for the browser extension and now pollutes the console for no particular reason if other libraries/frameworks use browser post messaging.

**Comment by mreuvers** [comment]
@TobiasWalle I just pushed 0.3.1 with your fix to npm, once ok can you close this issue?

Sorry that the pull request was closed but it always does that automatically on merge and I tend to forget that. So you can continue the chat here if you like.

**Comment by TobiasWalle** [comment]
@mreuvers Everything works fine now :) Thank you for accepting my pull request
The issue can be closed.

**Comment by mreuvers** [comment]
You're welcome and thank you for the pull request. :)
