### ISSUE TITLE
Allow easy customization of LogMessage / CategoryLogMessage for existing LoggerTypes

### ISSUE THREAD

**Issue by CSchulz** [mreuvers/typescript-logging#9]
At the moment the developer has to implement a complete new sub class, if he wants to overwrite `createDefaultLogMessage`.

It would be cool, if this method can be configured via closure or similar to change the generation of the message itself and nothing else.

**Comment by mreuvers** [comment]
Hello @CSchulz 

What do you mean exactly in this case? For custom loggers you already need to implement doLog(..) and effectively decide what the format will look like there.

Maybe you're talking about existing classes, such as ConsoleLoggerImpl and want to modify it for these?

**Comment by CSchulz** [comment]
I just want to change the layout of the message but want to use the same console logger implementation.

Yes you are right I can overwrite the implementation, but I think it could be nice just to have the possibility to overwrite the format by passing in another method to create the message. It should take the LogMessage object and return the string.

**Comment by mreuvers** [comment]
Hello @CSchulz 

Ok that's indeed for using an existing implementation then.

I will plan it in and it will be added for both the log4j style and category style logging. 
It can be applied then for all existing logging types (except for custom as that makes no sense).

Thanks for logging the issue.

**Comment by mreuvers** [comment]
Resolved, and released.
