### ISSUE TITLE
CategoryImpl does not pass down arguments in a correct way

### ISSUE THREAD

**Issue by jkorrek** [mreuvers/typescript-logging#93]
When I was looking at updating to the new major version I noticed a somewhat unexpected behaviour when using the category style logger.

I noticed, that the "args" always seemed to be wrapped into an additional array.
For example logging with a single argument `{ a: 1 }` would be passed to my log channel as `[ [ { a: 1 } ] ]`.

As far as I can tell, this is related to CategoryImpl, which is not using a spread operator when passing args to the actual logger.
[Changing the code like this fixes the issue for me](https://github.com/jkorrek/typescript-logging/commit/25c77d4268a5c2eea64c4db705a817138cf21fb1)

I would be happy to provide a pull request with these changes.

**Comment by mreuvers** [comment]
Hi there,

Thank you for reporting this. This seems like a bug indeed on first glance. 

I'll have a look at it soon, to make sure I can reproduce it as well. If so, it will be fixed with a minor patch version. I'll keep you informed here.

Thanks!

**Comment by mreuvers** [comment]
The issue was resolved by https://github.com/vauxite-org/typescript-logging/pull/94 (as to how you suggested). Some tests were added to cover as well.

In any case version 2.0.1 should be available in npm shortly.

I leave this issue open for a few more days so you can test it, please let me know if it works. Thanks!

**Comment by jkorrek** [comment]
Just tested with the new release - everything works as expected.
Thanks a lot for your quick response & help 👍
